version: '3.7'
services:
    irishealth:
        init: true
        build: 
          context: .
          dockerfile: Dockerfile
        image: irishealth:demo
        hostname: irishealth
        container_name: irishealth
        environment:
          - ISC_DATA_DIRECTORY=/IRIS
          # - ISC_CPF_MERGE_FILE=/ISC/iris.conf
        volumes: 
        - ./src/:/src
        - ./data:/data
        - databases:/databases
        - IRIS:/IRIS
        ports:
          - 51972:1972
          - 52021:52773
        command:
          # --key /tmp/iris.key
          -a /src/shell/init.sh
volumes:
  databases:
  IRIS:  
